language: ruby
before_install: gem install bundler
bundler_args: --without debug doc tooling
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx
  - rbx-2
notifications:
  irc: "irc.freenode.org#htty"
script: "bundle exec rake test"
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: 1.9.2
    - rvm: 1.9.3
    - rvm: ruby-head
    - rvm: ree
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx
    - rvm: rbx-2
branches:
  except:
    - /^gh-pages.*$/
